<?php 

add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles', 99);

function theme_enqueue_styles() 
{
	wp_enqueue_style( 'theme-style', get_stylesheet_uri() );
}


acf_add_local_field_group(array(
	'key' => 'group_605a3f5e343sddsf',
	'title' => 'Home Page Options',
	'fields' => array(
		array(
			'key' => 'field_605a3f5e76c034354',
			'label' => 'Page Builder',
			'name' => 'home_page_builder',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_603e96fe2ede6' => array(
					'key' => 'layout_603435',
					'name' => 'intro_section',
					'label' => 'Intro Section',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_605a4143e7fcc',
							'label' => 'Intro Type',
							'name' => 'intro_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'img_options',
								'id' => '',
							),
							'choices' => array(
								'intro_1' => 'Intro 1 <img src="'.get_template_directory_uri().'/assets/images/Intro/intro-0.png">',
								'intro_2' => 'Intro 2 <img src="'.get_template_directory_uri().'/assets/images/Intro/intro-1.png">',
								'intro_3' => 'Intro 3 <img src="'.get_template_directory_uri().'/assets/images/Intro/intro-3.png">',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_607987',
							'label' => 'Block Id',
							'name' => 'block_id',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_605a3f5e7e49a',
							'label' => 'Content Block',
							'name' => 'content_block',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_605a4170e7fcd',
							'label' => 'Content Position',
							'name' => 'content_position',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_605a4143e7fcc',
										'operator' => '!=',
										'value' => 'intro_3',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'left' => 'Left',
								'right' => 'Right',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_605a41b2e7fce43543',
							'label' => 'Video Embed URL',
							'name' => 'video_embed_url',
							'type' => 'text',
							'instructions' => 'Enter the URL of the video only',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_605a4143e7fcc',
										'operator' => '==',
										'value' => 'intro_3',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_605a41b2e7fce',
							'label' => 'Form Shortcode',
							'name' => 'form_shortcode',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_605a4143e7fcc',
										'operator' => '==',
										'value' => 'intro_2',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_605a41d4e7fd0',
							'label' => 'Background Image',
							'name' => 'background_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_605a4143e7fcc',
										'operator' => '==',
										'value' => 'intro_3',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_605a3f5e81edc',
							'label' => 'Button',
							'name' => 'button',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_605a4143e7fcc',
										'operator' => '!=',
										'value' => 'intro_3',
									),
								),
							),
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_605a3f5e8589e',
							'label' => 'Button Class',
							'name' => 'button_class',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_605a4143e7fcc',
										'operator' => '!=',
										'value' => 'intro_3',
									),
								),
							),
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'primary' => 'Primary',
								'secondary' => 'Secondary',
							),
							'default_value' => 'primary',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 1,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_605a3f5e8534534',
							'label' => 'Button Position',
							'name' => 'button_position',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_605a4143e7fcc',
										'operator' => '!=',
										'value' => 'intro_3',
									),
								),
							),
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'left' => 'Left',
								'right' => 'Right',
								'center' => 'Center',
							),
							'default_value' => 'left',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 1,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_603e98812c9dd' => array(
					'key' => 'layout_603e98812c9dd3453',
					'name' => 'content_section',
					'label' => 'Content Section',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_605a4346c587c56',
							'label' => 'Content Type',
							'name' => 'content_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'img_options',
								'id' => '',
							),
							'choices' => array(
								'content_1' => 'Content 1 <img src="'.get_template_directory_uri().'/assets/images/Content/content-1.png">',
								'content_2' => 'Content 2 <img src="'.get_template_directory_uri().'/assets/images/Content/content-2.png">',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_6079878346',
							'label' => 'Block Id',
							'name' => 'block_id',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_605a3f5eaa85d464',
							'label' => 'Content Block',
							'name' => 'content_block',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_605a431cc587a46',
							'label' => 'Content Position',
							'name' => 'content_position',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_605a4346c587c',
										'operator' => '!=',
										'value' => 'content_1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'left' => 'Left',
								'right' => 'Right',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_605a3f5eae2ca456',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_605a4346c587c',
										'operator' => '!=',
										'value' => 'content_1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => '',
							'preview_size' => 'medium',
							'library' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_605a3f5eb20346',
							'label' => 'Button',
							'name' => 'button',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_605a4329c587b456',
							'label' => 'Button Class',
							'name' => 'button_class',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'primary' => 'Primary',
								'secondary' => 'Secondary',
							),
							'default_value' => 'primary',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 1,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_605a3f5eb243543',
							'label' => 'Button 2',
							'name' => 'button_2',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_605a434353',
							'label' => 'Button Class 2',
							'name' => 'button_class_2',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'primary' => 'Primary',
								'secondary' => 'Secondary',
							),
							'default_value' => 'primary',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 1,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_603e98b02c9e3' => array(
					'key' => 'layout_603e98b02c9e3',
					'name' => 'gallery_section',
					'label' => 'Gallery Section',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_605a4cc0c587d',
							'label' => 'Gallery Type',
							'name' => 'gallery_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'img_options',
								'id' => '',
							),
							'choices' => array(
								'gallery_1' => 'Gallery 1 <img src="'.get_template_directory_uri().'/assets/images/Gallery/gallery-2.png">',
								'gallery_2' => 'Gallery 2 <img src="'.get_template_directory_uri().'/assets/images/Gallery/gallery-1.png">',
								'gallery_3' => 'Gallery 3 <img src="'.get_template_directory_uri().'/assets/images/Gallery/gallery-3.png">',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_607987798',
							'label' => 'Block Id',
							'name' => 'block_id',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_605a3f5ec09f4',
							'label' => 'Content Block',
							'name' => 'content_block',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_605a3f5ec444a',
							'label' => 'Gallery Column',
							'name' => 'gallery_column',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_605a4cc0c587d',
										'operator' => '==',
										'value' => 'gallery_1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_603e98d32c9e6',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Gallery Item',
							'sub_fields' => array(
								array(
									'key' => 'field_605a3f5fa076c',
									'label' => 'Image',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => '',
									'preview_size' => 'medium',
									'library' => '',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'field_605a3f5fa4127',
									'label' => 'Text',
									'name' => 'text',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
								),
							),
						),
						array(
							'key' => 'field_605a3f5ecbb5f',
							'label' => 'Gallery Items',
							'name' => 'gallery_items',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_605a4cc0c587d',
										'operator' => '==',
										'value' => 'gallery_2',
									),
								),
								array(
									array(
										'field' => 'field_605a4cc0c587d',
										'operator' => '==',
										'value' => 'gallery_3',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'insert' => 'append',
							'library' => 'all',
							'min' => '',
							'max' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_605a53bdc5881',
							'label' => 'Button',
							'name' => 'button',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_605a53c7c5882',
							'label' => 'Button Class',
							'name' => 'button_class',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'primary' => 'Primary',
								'secondary' => 'Secondary',
							),
							'default_value' => 'primary',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 1,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_605a3f5e8545634',
							'label' => 'Button Position',
							'name' => 'button_position',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'left' => 'Left',
								'right' => 'Right',
								'center' => 'Center',
							),
							'default_value' => 'left',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 1,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_603e99732c9f1' => array(
					'key' => 'layout_603e99732c9f1',
					'name' => 'features_section',
					'label' => 'Features Section',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_605a534dc587f',
							'label' => 'Feature Type',
							'name' => 'feature_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'img_options',
								'id' => '',
							),
							'choices' => array(
								'feature_1' => 'Feature 1 <img src="'.get_template_directory_uri().'/assets/images/Features/features-1.png">',
								'feature_2' => 'Feature 2 <img src="'.get_template_directory_uri().'/assets/images/Features/features-2.png">',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_60798746',
							'label' => 'Block Id',
							'name' => 'block_id',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_605a3f5ed31e6',
							'label' => 'Content Block',
							'name' => 'content_block',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_605a3f5ede29e',
							'label' => 'Feature',
							'name' => 'feature',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Feature',
							'sub_fields' => array(
								array(
									'key' => 'field_605a3f5fdc7b2',
									'label' => 'Image',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'medium',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'field_605a3f5fe02ec',
									'label' => 'Text',
									'name' => 'text',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
								),
							),
						),
						array(
							'key' => 'field_605a53d2c5883',
							'label' => 'Button',
							'name' => 'button',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_605a53d9c5884',
							'label' => 'Button Class',
							'name' => 'button_class',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'primary' => 'Primary',
								'secondary' => 'Secondary',
							),
							'default_value' => 'primary',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 1,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_605a3f589794',
							'label' => 'Button Position',
							'name' => 'button_position',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'left' => 'Left',
								'right' => 'Right',
								'center' => 'Center',
							),
							'default_value' => 'left',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 1,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_603e99ef2ca06' => array(
					'key' => 'layout_603e99ef2ca06',
					'name' => 'team_section',
					'label' => 'Team Section',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_605a542bc5885',
							'label' => 'Team Type',
							'name' => 'team_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'img_options',
								'id' => '',
							),
							'choices' => array(
								'team_1' => 'Team 1 <img src="'.get_template_directory_uri().'/assets/images/Team/team-0.png">',
								'team_2' => 'Team 2 <img src="'.get_template_directory_uri().'/assets/images/Team/team-1.png">',
								'team_3' => 'Team 3 <img src="'.get_template_directory_uri().'/assets/images/Team/team-2.png">',
								'team_4' => 'Team 4 <img src="'.get_template_directory_uri().'/assets/images/Team/team-3.png">',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_607987465',
							'label' => 'Block Id',
							'name' => 'block_id',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_605a3f5f03e75',
							'label' => 'Content Block',
							'name' => 'content_block',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_605a542bc5885',
										'operator' => '==',
										'value' => 'team_1',
									),
								),
								array(
									array(
										'field' => 'field_605a542bc5885',
										'operator' => '==',
										'value' => 'team_4',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_603e9b362ca31' => array(
					'key' => 'layout_603e9b362ca31',
					'name' => 'testimonial_section',
					'label' => 'Testimonial Section',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_605a5514c5888',
							'label' => 'Testimonial Type',
							'name' => 'testimonial_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'img_options',
								'id' => '',
							),
							'choices' => array(
								'testimonial_1' => 'Testimonial 1 <img src="'.get_template_directory_uri().'/assets/images/Testimonials/testimonial-2.png">',
								'testimonial_2' => 'Testimonial 2 <img src="'.get_template_directory_uri().'/assets/images/Testimonials/testimonial-1.png">',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_60798741686',
							'label' => 'Block Id',
							'name' => 'block_id',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_605a3f5f28670',
							'label' => 'Content Block',
							'name' => 'content_block',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_605a5514c5888',
										'operator' => '==',
										'value' => 'testimonial_1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_603e9b572ca35' => array(
					'key' => 'layout_603e9b572ca35',
					'name' => 'contact_section',
					'label' => 'Contact Section',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_605a554ec5889',
							'label' => 'Contact Type',
							'name' => 'contact_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'img_options',
								'id' => '',
							),
							'choices' => array(
								'contact_1' => 'Contact 1 <img src="'.get_template_directory_uri().'/assets/images/Contact/contact-1.png">',
								'contact_2' => 'Contact 2 <img src="'.get_template_directory_uri().'/assets/images/Contact/contact-2.png">',
								'contact_3' => 'Contact 3 <img src="'.get_template_directory_uri().'/assets/images/Contact/contact-3.png">',
								'contact_4' => 'Contact 4 <img src="'.get_template_directory_uri().'/assets/images/Contact/contact-4.png">',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_60798713256',
							'label' => 'Block Id',
							'name' => 'block_id',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_605a3f5f2c07d',
							'label' => 'Contact Block',
							'name' => 'contact_block',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_605a3f5f2fb15',
							'label' => 'Map Embed Code',
							'name' => 'map_embed_code',
							'type' => 'text',
							'instructions' => 'Paste your Google map embed code here',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_605a554ec5889',
										'operator' => '==',
										'value' => 'contact_1',
									),
								),
								array(
									array(
										'field' => 'field_605a554ec5889',
										'operator' => '==',
										'value' => 'contact_2',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_605a5576c588a',
							'label' => 'Contact Form Shortcode',
							'name' => 'contact_form_shortcode',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_603e9b362ca366' => array(
					'key' => 'layout_603e9b3798',
					'name' => 'blog_section',
					'label' => 'Blog Section',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6079878794',
							'label' => 'Block Id',
							'name' => 'block_id',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_605a899864967',
							'label' => 'Blog Heading',
							'name' => 'blog_heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_605a8978979',
							'label' => 'Blog Subheading',
							'name' => 'blog_subheading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_605a3f7987',
							'label' => 'Content Block',
							'name' => 'content_block',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_6064e6a51d471' => array(
					'key' => 'layout_6064e6a51d471',
					'name' => 'pricing_tables',
					'label' => 'Pricing Tables',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_605a3f53546',
							'label' => 'Content Block',
							'name' => 'content_block',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_6064e6ac44363',
							'label' => 'Pricing Type',
							'name' => 'pricing_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'img_options',
								'id' => '',
							),
							'choices' => array(
								'pricing_1' => 'Pricing 1 <img src="'.get_template_directory_uri().'/assets/images/Pricing/pricing-1.png">',
								'pricing_2' => 'Pricing 2 <img src="'.get_template_directory_uri().'/assets/images/Pricing/pricing-2.png">',
								'pricing_3' => 'Pricing 3 <img src="'.get_template_directory_uri().'/assets/images/Pricing/pricing-3.png">',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_6064e76544364',
							'label' => 'Pricing Options',
							'name' => 'pricing_options',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'row',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_6064e75654',
									'label' => 'Block Id',
									'name' => 'block_id',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_6064e77644365',
									'label' => 'Title',
									'name' => 'title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_6064e77b44366',
									'label' => 'Price',
									'name' => 'price',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_6064e78144367',
									'label' => 'Details',
									'name' => 'details',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_6064e79244368',
									'label' => 'Button',
									'name' => 'button',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
								),
								array(
									'key' => 'field_6064e7ab44369',
									'label' => 'Button Class',
									'name' => 'button_class',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'primary' => 'Primary',
										'secondary' => 'Secondary',
									),
									'default_value' => false,
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'field_6064e7c24436a',
									'label' => 'Icon',
									'name' => 'icon',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_6064e6ac44363',
												'operator' => '!=',
												'value' => 'pricing_2',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'url',
									'preview_size' => 'medium',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'field_6064edd3951bd',
									'label' => 'Add options',
									'name' => 'add_options',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => 0,
									'max' => 0,
									'layout' => 'table',
									'button_label' => '',
									'sub_fields' => array(
										array(
											'key' => 'field_6064ede8951be',
											'label' => 'Option',
											'name' => 'option',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
									),
								),
							),
						),
					),

					'min' => '',
					'max' => '',
				),
				'layout_6064f5e98a948' => array(
					'key' => 'layout_6064f5e98a948',
					'name' => 'faq_section',
					'label' => 'Faq Section',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_605a3f5ert',
							'label' => 'Content Block',
							'name' => 'content_block',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_6064f6048a94b',
							'label' => 'FAQ',
							'name' => 'faq_option',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_6064f60f8a94c',
							'min' => 0,
							'max' => 0,
							'layout' => 'row',
							'button_label' => 'Add question',
							'sub_fields' => array(
								array(
									'key' => 'field_6064f60f8a94c',
									'label' => 'Question',
									'name' => 'faq_question',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_6064f6148a94d',
									'label' => 'Answer',
									'name' => 'faq_answer',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
					),
				),
				'layout_603e9b362ca3134534' => array(
					'key' => 'layout_603e9b362ca3143534',
					'name' => 'partner_section',
					'label' => 'Partner Section',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6079865675',
							'label' => 'Block Id',
							'name' => 'block_id',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_605a6676',
							'label' => 'Content Block',
							'name' => 'content_block',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => '',
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Content',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-home.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'slug',
		5 => 'author',
		6 => 'format',
		7 => 'featured_image',
		8 => 'categories',
		9 => 'tags',
		10 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));